import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  bn: {
    // Branding & Header
    academyName: 'নেক্সটজেন একাডেমি',
    portalSubtitle: 'ডিজিটাল প্যারেন্ট ও স্টুডেন্ট পোর্টাল',
    tagline: 'আগামীর স্মার্ট শিক্ষার ডিজিটাল অভিভাবক প্ল্যাটফর্ম',
    searchPlaceholder: 'খুঁজুন (শিক্ষার্থী, রোল, নোটিশ...)',
    logout: 'লগআউট',
    notifications: 'নোটিফিকেশন',
    currentLanguage: 'বাংলা',
    switchLanguage: 'English এ পরিবর্তন করুন',

    // Roles
    roleAdmin: 'অ্যাডমিনিস্ট্রেটর',
    roleTeacher: 'শিক্ষক',
    roleParent: 'অভিভাবক',
    roleStudent: 'শিক্ষার্থী',

    // Navigation
    navDashboard: 'ড্যাশবোর্ড',
    navStudents: 'শিক্ষার্থী তালিকা',
    navTeachers: 'শিক্ষক তালিকা',
    navAttendance: 'শিক্ষার্থী উপস্থিতি',
    navTeacherAttendance: 'শিক্ষক উপস্থিতি ও টাইম লগ',
    navExams: 'অনলাইন পরীক্ষা ও মূল্যায়ন',
    navResults: 'ফলাফল ও মার্কশিট',
    navRoutine: 'ক্লাস রুটিন',
    navHomework: 'বাড়ির কাজ (Homework)',
    navMaterials: 'লেকচার নোট ও হ্যান্ডনোট',
    navTextbooks: 'পাঠ্যপুস্তক ও ই-বুক',
    navFees: 'ফি ও অনলাইন পেমেন্ট',
    navNotices: 'নোটিশ বোর্ড',
    navAuditLogs: 'অডিট লগ (নিরাপত্তা)',
    myAttendanceTime: 'আমার হাজিরা ও সময়সূচি',
    teacherAttendanceTitle: 'শিক্ষক উপস্থিতি ও আগমন-প্রস্থান ব্যবস্থাপনা',
    onlineExamsTitle: 'অনলাইন পরীক্ষা ও মূল্যায়ন কেন্দ্র',
    createExam: '+ নতুন পরীক্ষা তৈরি করুন',
    startExam: 'পরীক্ষা শুরু করুন',
    homeworkTitle: 'প্রতিদিনের বাড়ির কাজ',
    postHomework: '+ নতুন বাড়ির কাজ দিন',
    materialsTitle: 'লেকচার নোট ও অধ্যয়ন সামগ্রী',
    postMaterial: '+ নতুন নোট / শিট আপলোড করুন',
    textbooksTitle: 'পাঠ্যপুস্তক ও ই-বুক লাইব্রেরি',
    postTextbook: '+ নতুন পাঠ্যপুস্তক যুক্ত করুন',
    chapter: 'অধ্যায় / টপিক',
    topic: 'টপিক / বিষয়',
    description: 'বিবরণ',
    dueDate: 'জমা দেওয়ার শেষ তারিখ',
    assignedDate: 'প্রদানের তারিখ',
    attachments: 'সংযুক্তি / নোট',
    statusCompleted: 'সম্পন্ন',
    statusPending: 'বাকি আছে',
    markCompleted: 'সম্পন্ন চিহ্নিত করুন',
    markPending: 'বাকি চিহ্নিত করুন',
    downloadNote: 'নোট ডাউনলোড',
    navLiveClasses: 'অনলাইন লাইভ ক্লাস',
    liveClassesTitle: 'লাইভ অনলাইন ক্লাস ও ভিডিও ক্লাসরুম',
    createLiveClass: '+ নতুন লাইভ ক্লাস তৈরি করুন',
    liveNow: '🔴 লাইভ চলছে',
    upcomingClasses: 'আসন্ন লাইভ ক্লাস',
    recordedClasses: 'রেকর্ডেড ভিডিও লেকচার',
    joinLiveClass: 'এখনই ক্লাসে যুক্ত হন (Join Live)',
    watchRecording: 'ভিডিও রেকর্ডিং দেখুন',
    addRecordingLink: 'রেকর্ডেড ভিডিও লিঙ্ক যোগ করুন',
    recordingVideoUrl: 'রেকর্ডেড ভিডিও লিঙ্ক (YouTube / Drive / MP4)',
    recordingDuration: 'রেকর্ডিংয়ের দৈর্ঘ্য (যেমন: ৪৫ মিনিট)',
    notesAndSheets: 'ক্লাস নোট ও স্টাডি মেটেরিয়াল',
    meetingLink: 'মিটিং লিঙ্ক',
    meetingPassword: 'পাসকোড / পিন (ঐচ্ছিক)',
    platform: 'প্ল্যাটফর্ম',
    scheduleTime: 'তারিখ ও সময়সূচি',
    duration: 'স্থায়িত্ব (মিনিট)',
    allSections: 'সকল শাখা (All Sections)',
    liveAlertNotice: '⚠️ লাইভ ক্লাস রিমাইন্ডার:',
    startingInMinutes: 'মিনিটের মধ্যে শুরু হতে যাচ্ছে!',
    filterBySubject: 'বিষয় অনুযায়ী ফিল্টার...',
    searchLiveClasses: 'ক্লাসের শিরোনাম, বিষয় বা শিক্ষক খুঁজুন...',
    noLiveClassesFound: 'কোনো লাইভ ক্লাস পাওয়া যায়নি',
    endClass: 'ক্লাস শেষ করুন',
    startLiveNow: '🔴 এখনই লাইভ শুরু করুন',

    // Teacher Directory & Contact Info
    teacherDirectoryTitle: 'শিক্ষক প্রোফাইল ও কন্টাক্ট ডিরেক্টরি',
    teacherDirectorySubtitle: 'অভিভাবক ও শিক্ষার্থীদের জন্য সকল শিক্ষকের বিষয়ভিত্তিক প্রোফাইল ও সরাসরি যোগাযোগ ব্যবস্থা',
    searchTeachersPlaceholder: 'শিক্ষকের নাম, বিষয়, পদবি বা মোবাইল নম্বর দিয়ে খুঁজুন...',
    allDepartments: 'সকল বিভাগ / বিষয়',
    callNow: 'কল করুন',
    sendWhatsApp: 'হোয়াটসঅ্যাপ',
    sendSMS: 'এসএমএস',
    sendEmail: 'ইমেইল পাঠান',
    phoneHiddenPrivate: '🔒 শিক্ষকের অনুরোধে মোবাইল নম্বরটি গোপন রাখা হয়েছে',
    requestContact: 'যোগাযোগের অনুরোধ পাঠান',
    contactNumber: 'মোবাইল নম্বর',
    officeRoom: 'কক্ষ / ল্যাব নম্বর',
    officeHours: 'সাক্ষাৎ ও যোগাযোগের সময়',
    assignedClasses: 'নির্ধারিত শ্রেণি ও শাখা',
    classTeacherBadge: 'শ্রেণি শিক্ষক',
    qualifications: 'শিক্ষাগত যোগ্যতা',
    specialization: 'বিশেষায়িত বিষয়',
    myProfileSettings: 'আমার প্রোফাইল ও যোগাযোগ সেটিংস',
    privacyToggleLabel: 'অভিভাবক ও শিক্ষার্থীদের কাছে আমার মোবাইল নম্বর প্রদর্শন করুন',
    privacyVisibleStatus: 'বর্তমানে মোবাইল নম্বরটি দৃশ্যমান আছে',
    privacyHiddenStatus: 'বর্তমানে মোবাইল নম্বরটি গোপন রাখা হয়েছে',

    // Batch & Routine Management
    navBatchesRoutine: 'ব্যাচ ও ক্লাস রুটিন',
    batchManagementTitle: 'ব্যাচ ম্যানেজমেন্ট',
    batchManagementSubtitle: 'শ্রেণিভিত্তিক ব্যাচ তৈরি, আসন সংখ্যা ট্র্যাকিং, শিক্ষার্থী স্থানান্তর ও ফি নিয়ন্ত্রণ',
    classRoutineTitle: 'সাপ্তাহিক ক্লাস রুটিন',
    classRoutineSubtitle: 'দিন ও সময়ভিত্তিক বিষয়-শিক্ষক শিডিউল, লাইভ গ্রিড ও প্রিন্ট রুটিন',
    createNewBatch: '+ নতুন ব্যাচ তৈরি করুন',
    editBatch: 'ব্যাচ সম্পাদনা',
    deleteBatch: 'ব্যাচ মুছুন',
    batchNameBn: 'ব্যাচের নাম (বাংলা)',
    batchNameEn: 'ব্যাচের নাম (English)',
    seatCapacity: 'সর্বোচ্চ আসন সংখ্যা',
    enrolledStudents: 'ভর্তি শিক্ষার্থী',
    availableSeats: 'খালি আসন',
    occupancyRate: 'আসন পূর্ণতার হার',
    monthlyFee: 'মাসিক ফি',
    shift: 'শিফট / সময়সূচি',
    mentorTeacher: 'তত্ত্বাবধায়ক শিক্ষক (Mentor)',
    transferStudent: 'ব্যাচ শিফট / স্থানান্তর',
    transferStudentTitle: 'শিক্ষার্থী ব্যাচ স্থানান্তর',
    transferStudentSubtitle: 'এক ব্যাচ থেকে অন্য ব্যাচে শিক্ষার্থী স্থানান্তর ও হিস্ট্রি সংরক্ষণ',
    targetBatch: 'গন্তব্য ব্যাচ নির্বাচন করুন',
    transferReason: 'স্থানান্তরের কারণ',
    transferDate: 'স্থানান্তরের তারিখ',
    transferHistory: 'স্থানান্তর হিস্ট্রি',
    addRoutineSlot: '+ রুটিন পিরিয়ড যুক্ত করুন',
    editRoutineSlot: 'পিরিয়ড স্লট সম্পাদনা',
    timeSlot: 'সময়সূচি',
    printRoutine: 'রুটিন প্রিন্ট করুন',
    downloadRoutinePdf: 'রুটিন ডাউনলোড (PDF)',
    conflictError: 'সময়সূচি সংঘাত (Schedule Conflict)!',

    // Results & Report Card Generator
    navResultsReport: 'ফলাফল ও মার্কশিট',
    resultsManagerTitle: 'ফলাফল ও মার্কশিট জেনারেটর',
    resultsManagerSubtitle: 'বাল্ক মার্কস এন্ট্রি, জাতীয় গ্রেডিং GPA ইঞ্জিন, স্বয়ংক্রিয় মেধাতালিকা ও ৩৬০° রিপোর্ট কার্ড',
    marksEntryTab: 'নম্বর এন্ট্রি (Marks Entry)',
    meritListTab: 'মেধাতালিকা ও সামারি (Merit List)',
    reportCardTab: '৩৬০° রিপোর্ট কার্ড (Report Card)',
    tabulationSheetTab: 'ট্যাবুল্যাশন শিট (Tabulation)',
    examTerm: 'পরীক্ষার নাম / টার্ম',
    cqMarks: 'রচনামূলক (CQ)',
    mcqMarks: 'বহুনির্বাচনী (MCQ)',
    practicalMarks: 'ব্যবহারিক',
    obtainedMarks: 'প্রাপ্ত নম্বর',
    highestInClass: 'সর্বোচ্চ নম্বর',
    gradePoint: 'গ্রেড পয়েন্ট',
    letterGrade: 'লেটার গ্রেড',
    meritRank: 'মেধা স্থান (Rank)',
    passRate: 'পাশের হার',
    gpa5Count: 'জিপিএ ৫.০০ প্রাপ্ত',
    classTopper: 'ক্লাস টপার',
    bulkSaveMarks: 'সকল শিক্ষার্থীর নম্বর সংরক্ষণ করুন',
    printReportCard: 'মার্কশিট প্রিন্ট (PDF)',
    printTabulation: 'ট্যাবুল্যাশন প্রিন্ট',
    classTeacherRemarks: 'শ্রেণি শিক্ষকের মন্তব্য',
    principalRemarks: 'অধ্যক্ষের মন্তব্য',

    // Accounts & Payroll Management
    navAccountsPayroll: 'হিসাব ও পেরোল',
    accountsPayrollTitle: 'হিসাব ও বেতন ব্যবস্থাপনা (Accounts & Payroll)',
    accountsPayrollSubtitle: 'ক্যাটাগরিভিত্তিক খরচ ভাউচার, শিক্ষক সম্মানী ও বেতন, পে-স্লিপ এবং ক্যাশবুক লেজার স্টেটমেন্ট',
    analyticsTab: 'আর্থিক ড্যাশবোর্ড (P&L)',
    expensesTab: 'খরচ ব্যবস্থাপনা (Expenses)',
    payrollTab: 'শিক্ষক পেরোল ও বেতন (Payroll)',
    cashbookTab: 'ক্যাশবুক ও লেজার (Cashbook)',
    totalFeeIncome: 'মোট ফি আদায়',
    totalGeneralExpenses: 'মোট সাধারণ খরচ',
    totalSalaryDisbursed: 'পরিশোধিত শিক্ষক বেতন',
    netBalance: 'নিট লাভ / ব্যালেন্স',
    addExpenseVoucher: '+ নতুন খরচ এন্ট্রি',
    expenseCategory: 'খরচের খাত / ক্যাটাগরি',
    expenseTitle: 'খরচের শিরোনাম',
    expenseAmount: 'পরিমাণ (টাকা)',
    expenseDate: 'খরচের তারিখ',
    paymentMethod: 'পরিশোধের মাধ্যম',
    recipientName: 'প্রাপকের নাম / ভেন্ডর',
    voucherNo: 'ভাউচার নম্বর',
    generateMonthlyPayroll: 'মাসিক বেতন প্রস্তুত করুন',
    disburseSalary: 'বেতন পরিশোধ করুন',
    printPayslip: 'পে-স্লিপ প্রিন্ট (PDF)',
    printCashbook: 'ক্যাশবুক প্রিন্ট',
    netPayable: 'সর্বমোট প্রদেয় বেতন',

    // Admin Settings & Role-Based Access Control
    navAdminSettings: 'সিস্টেম ও রোল সেটিংস',
    navPaymentSettings: 'পেমেন্ট সেটিংস',
    settingsHubTitle: 'সিস্টেম কনফিগারেশন ও সাইট সেটিংস',
    adminSettingsSubtitle: 'ইনস্টিটিউট প্রোফাইল, ব্র্যান্ডিং, স্টাফ ইউজার এবং মডিউলভিত্তিক গ্রানুলার অ্যাক্সেস কন্ট্রোল',
    instituteProfileTab: 'ইনস্টিটিউট প্রোফাইল ও ব্র্যান্ডিং',
    staffUsersTab: 'স্টাফ ও সাব-অ্যাডমিন',
    rolesPermissionsTab: 'রোল ও পারমিশন কন্ট্রোল',
    instituteNameBn: 'প্রতিষ্ঠানের নাম (বাংলা)',
    instituteNameEn: 'Institute Name (English)',
    instituteTagline: 'ট্যাগলাইন / মূলমন্ত্র',
    instituteCode: 'EIIN / রেজিস্ট্রেশন কোড',
    institutePhone: 'হটলাইন / মোবাইল নম্বর',
    instituteEmail: 'প্রাতিষ্ঠানিক ইমেইল',
    instituteAddress: 'ক্যাম্পাস পূর্ণাঙ্গ ঠিকানা',
    instituteWebsite: 'অফিসিয়াল ওয়েবসাইট',
    printFooterNote: 'মানি রিসিট ফুটার নোট',
    admitCardInstructions: 'অ্যাডমিট কার্ড নির্দেশনাবলী',
    addNewStaff: '+ নতুন স্টাফ / অ্যাডমিন',
    createCustomRole: '+ নতুন রোল তৈরি',
    rolePermissions: 'মডিউল পারমিশন ম্যাট্রিক্স',

    // Digital Admission & Online Intake
    navAdmissions: 'অনলাইন ভর্তি',
    onlineAdmissionTitle: 'ডিজিটাল ভর্তি ও অনলাইন আবেদন (Online Admission)',
    onlineAdmissionSubtitle: 'শিক্ষার্থী ভর্তি আবেদন, তথ্য যাচাই-বাছাই, অটো রোল জেনারেশন ও মানি রিসিট',
    publicApplyOnline: 'অনলাইন ভর্তি আবেদন',
    trackApplication: 'আবেদন অগ্রগতি ট্র্যাকিং',
    studentNameBn: 'শিক্ষার্থীর নাম (বাংলা)',
    studentNameEn: 'Student Name (English)',
    targetClass: 'ভর্তির কাঙ্ক্ষিত শ্রেণি',
    admissionTargetBatch: 'কাঙ্ক্ষিত ব্যাচ',
    bloodGroup: 'রক্তের গ্রুপ',
    dob: 'জন্ম তারিখ',
    gender: 'লিঙ্গ',
    previousSchool: 'পূর্ববর্তী স্কুলের নাম',
    previousGpa: 'পূর্ববর্তী পরীক্ষার জিপিএ',
    guardianName: 'অভিভাবকের পুরো নাম',
    guardianPhone: 'অভিভাবকের মোবাইল নম্বর',
    guardianProfession: 'অভিভাবকের পেশা',
    guardianEmail: 'অভিভাবকের ইমেইল',
    address: 'বর্তমান ও স্থায়ী ঠিকানা',
    uploadPhoto: 'পাসপোর্ট সাইজ ছবি আপলোড',
    uploadMarksheet: 'পূর্ববর্তী পরীক্ষার মার্কশিট / সার্টিফিকেট',
    submitApplication: 'আবেদন দাখিল করুন',
    trackingId: 'আবেদন ট্র্যাকিং কোড',
    approveAdmission: 'ভর্তি অনুমোদন করুন',
    rejectAdmission: 'আবেদন বাতিল করুন',
    admissionFeeReceipt: 'ভর্তি মানি রিসিট',

    // Data Backup & Export
    navDataBackup: 'ডাটা ব্যাকআপ',
    dataBackupTitle: 'সম্পূর্ণ ডাটাবেজ ব্যাকআপ ও এক্সপোর্ট (Data Backup & Export)',
    dataBackupSubtitle: 'এক ক্লিকে এক্সেল/CSV এক্সপোর্ট, রিলেশনাল SQL ডাম্প এবং সম্পূর্ণ JSON ডাটাবেজ ব্যাকআপ',
    fullJsonBackup: 'সম্পূর্ণ JSON ব্যাকআপ',
    fullSqlDump: 'রিলেশনাল SQL ডাম্প (.sql)',
    exportCsv: 'CSV এক্সপোর্ট',
    exportExcel: 'এক্সেল ফরম্যাট',
    databaseTablesSummary: 'ডাটাবেজ টেবিল সারসংক্ষেপ',
    totalDatabaseRecords: 'মোট সংরক্ষিত ডাটা রেকর্ড',
    lastBackupTime: 'সর্বশেষ ব্যাকআপ সময়',

    // Bulk SMS & Dynamic Templates
    navSMS: 'এসএমএস ও নোটিফিকেশন',
    smsTitle: 'বাল্ক এসএমএস ও স্মার্ট নোটিফিকেশন সিস্টেম',
    smsSubtitle: 'ফিল্টারভিত্তিক এসএমএস প্রেরণ, ডায়নামিক ভ্যারিয়েবল টেমপ্লেট ও লাইভ ডেলিভারি হিস্ট্রি',
    smsBalance: 'অবশিষ্ট এসএমএস ব্যালেন্স',
    smsPurchased: 'মোট ক্রয়কৃত এসএমএস',
    smsSentTotal: 'মোট প্রেরিত এসএমএস',
    smsDeliveryRate: 'ডেলিভারি সাকসেস রেট',
    smsComposeTab: 'এসএমএস কম্পোজ ও প্রেরণ',
    smsLogsTab: 'ডেলিভারি হিস্ট্রি ও লগ',
    smsTemplatesTab: 'সংরক্ষিত টেমপ্লেট',
    targetRecipients: 'প্রাপক নির্বাচন',
    dueOnlyStudents: 'শুধু বকেয়া ফি থাকা শিক্ষার্থী',
    templateSelector: 'রেডিমেড টেমপ্লেট নির্বাচন',
    dynamicVariables: 'ডায়নামিক ভ্যারিয়েবলস (ক্লিক করে ইনসার্ট করুন)',
    livePreview: 'লাইভ প্রিভিউ ও এসএমএস কাউন্টার',
    sendBulkSMSBtn: 'বাল্ক এসএমএস প্রেরণ করুন',

    // Common
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল',
    confirm: 'নিশ্চিত করুন',
    processing: 'প্রক্রিয়াকরণ হচ্ছে...',
    success: 'সফল হয়েছে',
    error: 'ত্রুটি',
    viewDetails: 'বিস্তারিত দেখুন',
    downloadPdf: 'পিডিএফ ডাউনলোড',
    printReceipt: 'রসিদ প্রিন্ট',
    roll: 'রোল',
    class: 'শ্রেণি',
    section: 'শাখা',
    studentId: 'আইডি নম্বর',
    phone: 'মোবাইল',
    date: 'তারিখ',
    status: 'অবস্থা',
    amount: 'টাকার পরিমাণ',
    action: 'পদক্ষেপ',
    active: 'সক্রিয়',
    inactive: 'নিষ্ক্রিয়',

    // Login Page
    welcomeBack: 'স্বাগতম NextGen একাডেমিতে',
    loginTitle: 'পোর্টালে লগইন করুন',
    loginSubtitle: 'আপনার রোল অনুযায়ী ইমেইল, স্টুডেন্ট আইডি ও পাসওয়ার্ড প্রদান করে প্রবেশ করুন',
    emailLabel: 'ইমেইল অথবা স্টুডেন্ট আইডি / ফোন',
    loginPlaceholder: 'ইমেইল অথবা স্টুডেন্ট আইডি',
    passwordLabel: 'পাসওয়ার্ড',
    loginButton: 'লগইন করুন',
    demoLoginsTitle: '⚡ ১-ক্লিকে ডেমো লগইন পরীক্ষা করুন:',
    demoAdmin: 'অ্যাডমিন ডেমো',
    demoTeacher: 'শিক্ষক ডেমো',
    demoParent: 'অভিভাবক ডেমো',
    demoStudent: 'শিক্ষার্থী ডেমো',

    // Admin Dashboard
    adminTitle: 'একাডেমি প্রশাসনিক নিয়ন্ত্রণ কেন্দ্র',
    totalStudents: 'মোট শিক্ষার্থী',
    totalTeachers: 'মোট শিক্ষক',
    attendanceToday: 'আজকের গড় উপস্থিতি',
    feesCollection: 'ফি আদায় অনুপাত',
    totalBilled: 'মোট ধার্যকৃত ফি',
    totalCollected: 'আদায়কৃত পরিমাণ',
    totalPending: 'বকেয়া পাওনা',
    publishNotice: '+ নতুন নোটিশ প্রকাশ করুন',
    recentAuditLogs: 'সাম্প্রতিক সিস্টেম অডিট লগ',
    allStudentsDir: 'সকল শিক্ষার্থীর তালিকা',
    academicYear: 'শিক্ষাবর্ষ ২০২৬',

    // Teacher Dashboard
    teacherTitle: 'শিক্ষক পোর্টাল ও গ্রেডবুক',
    takeAttendance: 'উপস্থিতি গ্রহণ করুন',
    inputMarks: 'পরীক্ষার নম্বর এন্ট্রি',
    myAssignedClasses: 'আমার নির্ধারিত ক্লাস ও বিষয়',
    markAllPresent: 'সকলকে উপস্থিত চিহ্নিত করুন',
    submitAttendance: 'উপস্থিতি সংরক্ষণ করুন',
    saveMarks: 'নম্বর সংরক্ষণ করুন',
    subject: 'বিষয়',
    teacherRemarks: 'শিক্ষকের মন্তব্য',

    // Parent Dashboard
    parentTitle: 'অভিভাবক পোর্টাল',
    selectChild: 'সন্তান নির্বাচন করুন:',
    childOverview: 'শিক্ষার্থীর সারসংক্ষেপ',
    overallAttendance: 'সার্বিক উপস্থিতি',
    currentGPA: 'বর্তমান জিপিএ',
    dueFees: 'বকেয়া ফি',
    payNow: 'অনলাইনে ফি পরিশোধ করুন',
    paidStatus: 'পরিশোধিত',
    unpaidStatus: 'অপরিশোধিত',
    viewReportCard: 'রিপোর্ট কার্ড দেখুন',

    // Student Dashboard
    studentTitle: 'শিক্ষার্থী পোর্টাল',
    digitalIdCard: 'ডিজিটাল স্টুডেন্ট আইডি কার্ড',
    todaySchedule: 'আজকের ক্লাসের সময়সূচি',
    examRoutine: 'পরীক্ষার সময়সূচি',
    admissionDate: 'ভর্তির তারিখ',

    // Payment Modal (bKash/Nagad/Card simulation)
    paymentModalTitle: 'ডিজিটাল ফি পেমেন্ট গেটওয়ে (সিমুলেশন)',
    selectMethod: 'পেমেন্ট মাধ্যম নির্বাচন করুন:',
    enterPhone: 'বিকাশ / নগদ মোবাইল নম্বর',
    enterPin: '৪-সংখ্যার সিমুলেশন পিন (যেকোনো)',
    confirmPayment: '৳ পরিশোধ নিশ্চিত করুন',
    paymentSuccess: 'অভিনন্দন! আপনার ফি পেমেন্ট সফলভাবে সম্পন্ন হয়েছে।',
    transactionId: 'ট্রানজেকশন আইডি',
    receiptDownload: 'ডিজিটাল মানি রিসিট ডাউনলোড করুন'
  },
  en: {
    // Branding & Header
    academyName: 'NextGen Academy',
    portalSubtitle: 'Digital Parent & Student Portal',
    tagline: 'Next-Generation Smart Education Management Platform',
    searchPlaceholder: 'Search (student, roll, notice...)',
    logout: 'Logout',
    notifications: 'Notifications',
    currentLanguage: 'English',
    switchLanguage: 'বাংলায় পরিবর্তন করুন',

    // Roles
    roleAdmin: 'Administrator',
    roleTeacher: 'Teacher',
    roleParent: 'Parent / Guardian',
    roleStudent: 'Student',

    // Navigation
    navDashboard: 'Dashboard',
    navStudents: 'Students Directory',
    navTeachers: 'Teachers Directory',
    navAttendance: 'Student Attendance',
    navTeacherAttendance: 'Teacher Attendance & Time Log',
    navExams: 'Online Exams & Tests',
    navResults: 'Results & Report Card',
    navRoutine: 'Class Routine',
    navHomework: 'Daily Homework',
    navMaterials: 'Study Materials & Notes',
    navTextbooks: 'Digital Textbooks',
    navFees: 'Fees & Online Payment',
    navNotices: 'Notice Board',
    navAuditLogs: 'Security Audit Logs',
    myAttendanceTime: 'My Attendance & Time Log',
    teacherAttendanceTitle: 'Faculty Attendance & In-Out Timesheet',
    onlineExamsTitle: 'Online Examination & Assessment Center',
    createExam: '+ Create New Exam',
    startExam: 'Start Exam',
    homeworkTitle: 'Daily Homework & Tasks',
    postHomework: '+ Post Daily Homework',
    materialsTitle: 'Study Materials & Lecture Notes',
    postMaterial: '+ Upload Study Material',
    textbooksTitle: 'Digital Textbooks & E-Library',
    postTextbook: '+ Add New Textbook',
    chapter: 'Chapter / Topic',
    topic: 'Topic / Subject',
    description: 'Description',
    dueDate: 'Submission Deadline',
    assignedDate: 'Assigned Date',
    attachments: 'Attachment / Note',
    statusCompleted: 'Completed',
    statusPending: 'Pending',
    markCompleted: 'Mark as Completed',
    markPending: 'Mark as Pending',
    navLiveClasses: 'Live Classes',
    liveClassesTitle: 'Live Classes & Video Classroom',
    createLiveClass: '+ Schedule Live Class',
    liveNow: '🔴 Live Now',
    upcomingClasses: 'Upcoming Classes',
    recordedClasses: 'Recorded Video Lectures',
    joinLiveClass: 'Join Live Class Now',
    watchRecording: 'Watch Recording',
    addRecordingLink: 'Add Recording Link',
    recordingVideoUrl: 'Recording Video Link (YouTube / Drive / MP4)',
    recordingDuration: 'Recording Duration (e.g. 45 mins)',
    notesAndSheets: 'Lecture Notes & Study Sheets',
    meetingLink: 'Meeting Link',
    meetingPassword: 'Passcode / PIN (Optional)',
    platform: 'Platform',
    scheduleTime: 'Schedule Date & Time',
    duration: 'Duration (Mins)',
    allSections: 'All Sections',
    liveAlertNotice: '⚠️ Live Class Alert:',
    startingInMinutes: 'minutes remaining until start!',
    filterBySubject: 'Filter by Subject...',
    searchLiveClasses: 'Search class title, subject or teacher...',
    noLiveClassesFound: 'No live classes found',
    endClass: 'End Class',
    startLiveNow: '🔴 Start Live Now',

    // Teacher Directory & Contact Info
    teacherDirectoryTitle: 'Teacher Directory & Faculty Contact Info',
    teacherDirectorySubtitle: 'Direct contact information, faculty profiles, and office hours for parents and students',
    searchTeachersPlaceholder: 'Search faculty by name, subject, designation, phone or room...',
    allDepartments: 'All Departments / Subjects',
    callNow: 'Call Now',
    sendWhatsApp: 'WhatsApp Chat',
    sendSMS: 'Send SMS',
    sendEmail: 'Send Email',
    phoneHiddenPrivate: '🔒 Phone number is kept private by teacher',
    requestContact: 'Request Contact',
    contactNumber: 'Mobile Number',
    officeRoom: 'Room / Lab No.',
    officeHours: 'Office / Contact Hours',
    assignedClasses: 'Assigned Classes & Sections',
    classTeacherBadge: 'Class Teacher',
    qualifications: 'Educational Qualifications',
    specialization: 'Specialization / Dept',
    myProfileSettings: 'My Profile & Privacy Settings',
    privacyToggleLabel: 'Make my mobile number visible to parents and students',
    privacyVisibleStatus: 'Mobile number is currently visible',
    privacyHiddenStatus: 'Mobile number is currently hidden',

    // Batch & Routine Management
    navBatchesRoutine: 'Batches & Routine',
    batchManagementTitle: 'Batch Management',
    batchManagementSubtitle: 'Class-wise batches, seat capacity tracking, student reallocation and fees',
    classRoutineTitle: 'Weekly Class Routine',
    classRoutineSubtitle: 'Day and period-wise timetable, live grid and printable routine',
    createNewBatch: '+ Create New Batch',
    editBatch: 'Edit Batch',
    deleteBatch: 'Delete Batch',
    batchNameBn: 'Batch Name (Bengali)',
    batchNameEn: 'Batch Name (English)',
    seatCapacity: 'Seat Capacity',
    enrolledStudents: 'Enrolled Students',
    availableSeats: 'Available Seats',
    occupancyRate: 'Occupancy Rate',
    monthlyFee: 'Monthly Fee',
    shift: 'Shift / Timing',
    mentorTeacher: 'Mentor Teacher',
    transferStudent: 'Shift / Transfer Batch',
    transferStudentTitle: 'Transfer Student Batch',
    transferStudentSubtitle: 'Reallocate student to another batch with audit trail',
    targetBatch: 'Select Destination Batch',
    transferReason: 'Reason for Transfer',
    transferDate: 'Effective Date',
    transferHistory: 'Transfer History',
    addRoutineSlot: '+ Add Routine Slot',
    editRoutineSlot: 'Edit Routine Slot',
    timeSlot: 'Time Slot',
    printRoutine: 'Print Timetable',
    downloadRoutinePdf: 'Download Timetable (PDF)',
    conflictError: 'Schedule Conflict!',

    // Results & Report Card Generator
    navResultsReport: 'Results & Report Card',
    resultsManagerTitle: 'Results & Report Card Hub',
    resultsManagerSubtitle: 'Bulk marks entry, national GPA engine, automatic merit list and 360° report card',
    marksEntryTab: 'Marks Entry',
    meritListTab: 'Merit List & Summary',
    reportCardTab: '360° Report Card',
    tabulationSheetTab: 'Tabulation Sheet',
    examTerm: 'Exam Term',
    cqMarks: 'Creative (CQ)',
    mcqMarks: 'MCQ',
    practicalMarks: 'Practical',
    obtainedMarks: 'Obtained Marks',
    highestInClass: 'Highest in Class',
    gradePoint: 'Grade Point',
    letterGrade: 'Letter Grade',
    meritRank: 'Merit Rank',
    passRate: 'Pass Rate',
    gpa5Count: 'GPA 5.00 Count',
    classTopper: 'Class Topper',
    bulkSaveMarks: 'Save All Marks (Bulk)',
    printReportCard: 'Print Report Card (PDF)',
    printTabulation: 'Print Tabulation',
    classTeacherRemarks: 'Class Teacher Remarks',
    principalRemarks: 'Principal Remarks',

    // Accounts & Payroll Management
    navAccountsPayroll: 'Accounts & Payroll',
    accountsPayrollTitle: 'Accounts & Payroll Management',
    accountsPayrollSubtitle: 'Expense vouchers, teacher salary disbursement, digital pay-slips and cashbook ledger',
    analyticsTab: 'Financial P&L',
    expensesTab: 'Expense Log',
    payrollTab: 'Teacher Payroll',
    cashbookTab: 'Cashbook & Ledger',
    totalFeeIncome: 'Total Fee Revenue',
    totalGeneralExpenses: 'Total General Expenses',
    totalSalaryDisbursed: 'Total Salaries Paid',
    netBalance: 'Net Operating Profit',
    addExpenseVoucher: '+ New Expense Voucher',
    expenseCategory: 'Expense Category',
    expenseTitle: 'Expense Title',
    expenseAmount: 'Amount (৳)',
    expenseDate: 'Expense Date',
    paymentMethod: 'Payment Method',
    recipientName: 'Recipient / Vendor',
    voucherNo: 'Voucher No',
    generateMonthlyPayroll: 'Generate Monthly Payroll',
    disburseSalary: 'Disburse Salary',
    printPayslip: 'Print Pay Slip (PDF)',
    printCashbook: 'Print Cashbook',
    netPayable: 'Net Payable Salary',

    // Admin Settings & Role-Based Access Control
    navAdminSettings: 'Settings & Permissions',
    navPaymentSettings: 'Payment Settings',
    adminSettingsTitle: 'Admin Settings & RBAC Hub',
    adminSettingsSubtitle: 'Institute profile, branding, staff management and modular granular access permissions',
    instituteProfileTab: 'Institute Profile & Branding',
    staffUsersTab: 'Staff & Sub-Admins',
    rolesPermissionsTab: 'Roles & RBAC Matrix',
    instituteNameBn: 'Institute Name (Bengali)',
    instituteNameEn: 'Institute Name (English)',
    instituteTagline: 'Institute Tagline',
    instituteCode: 'Registration / EIIN Code',
    institutePhone: 'Helpline / Phone',
    instituteEmail: 'Official Email',
    instituteAddress: 'Campus Address',
    instituteWebsite: 'Official Website',
    printFooterNote: 'Receipt Footer Note',
    admitCardInstructions: 'Admit Card Instructions',
    addNewStaff: '+ Add Staff / Admin',
    createCustomRole: '+ Create Custom Role',
    rolePermissions: 'Module Permission Matrix',

    // Digital Admission & Online Intake
    navAdmissions: 'Online Admissions',
    onlineAdmissionTitle: 'Online Admission & Student Intake',
    onlineAdmissionSubtitle: 'Online application review, applicant vetting, auto roll engine and admission receipts',
    publicApplyOnline: 'Apply Online for Admission',
    trackApplication: 'Track Application Status',
    studentNameBn: 'Student Name (Bengali)',
    studentNameEn: 'Student Name (English)',
    targetClass: 'Target Class',
    admissionTargetBatch: 'Target Batch',
    bloodGroup: 'Blood Group',
    dob: 'Date of Birth',
    gender: 'Gender',
    previousSchool: 'Previous School Name',
    previousGpa: 'Previous Exam GPA',
    guardianName: 'Guardian Name',
    guardianPhone: 'Guardian Mobile Number',
    guardianProfession: 'Guardian Profession',
    guardianEmail: 'Guardian Email',
    address: 'Address',
    uploadPhoto: 'Upload Passport Photo',
    uploadMarksheet: 'Upload Marksheet / Certificate',
    submitApplication: 'Submit Application',
    trackingId: 'Application Tracking ID',
    approveAdmission: 'Approve Admission',
    rejectAdmission: 'Reject Application',
    admissionFeeReceipt: 'Admission Fee Receipt',

    // Data Backup & Export
    navDataBackup: 'Data Backup',
    dataBackupTitle: 'Data Backup & Database Export System',
    dataBackupSubtitle: 'One-click Excel/CSV export, relational SQL dump, and full JSON database backups',
    fullJsonBackup: 'Full JSON Backup',
    fullSqlDump: 'Relational SQL Dump (.sql)',
    exportCsv: 'Export CSV',
    exportExcel: 'Excel Format',
    databaseTablesSummary: 'Database Tables Summary',
    totalDatabaseRecords: 'Total Database Records',
    lastBackupTime: 'Last Backup Timestamp',

    // Bulk SMS & Dynamic Templates
    navSMS: 'SMS & Notifications',
    smsTitle: 'Bulk SMS & Smart Dynamic Notifications',
    smsSubtitle: 'Filter-based SMS dispatch, dynamic variables, live preview & delivery history',
    smsBalance: 'Remaining SMS Balance',
    smsPurchased: 'Total Purchased',
    smsSentTotal: 'Total Sent',
    smsDeliveryRate: 'Delivery Success Rate',
    smsComposeTab: 'Compose & Dispatch',
    smsLogsTab: 'Delivery Logs',
    smsTemplatesTab: 'Saved Templates',
    targetRecipients: 'Target Recipients',
    dueOnlyStudents: 'Due Fee Students Only',
    templateSelector: 'Select Preset Template',
    dynamicVariables: 'Dynamic Variables (Click to insert)',
    livePreview: 'Live Preview & SMS Counter',
    sendBulkSMSBtn: 'Send Bulk SMS Now',

    // Common
    save: 'Save Changes',
    cancel: 'Cancel',
    confirm: 'Confirm',
    processing: 'Processing...',
    success: 'Success',
    error: 'Error',
    viewDetails: 'View Details',
    downloadPdf: 'Download PDF',
    printReceipt: 'Print Receipt',
    roll: 'Roll',
    class: 'Class',
    section: 'Section',
    studentId: 'Student ID',
    phone: 'Phone',
    date: 'Date',
    status: 'Status',
    amount: 'Amount',
    action: 'Action',
    active: 'Active',
    inactive: 'Inactive',

    // Login Page
    welcomeBack: 'Welcome to NextGen Academy',
    loginTitle: 'Sign in to Portal',
    loginSubtitle: 'Enter your institutional email, Student ID, or phone to continue',
    emailLabel: 'Email, Student ID or Phone',
    loginPlaceholder: 'Email or Student ID',
    passwordLabel: 'Password',
    loginButton: 'Sign In',
    demoLoginsTitle: '⚡ Quick 1-Click Demo Login Test:',
    demoAdmin: 'Admin Demo',
    demoTeacher: 'Teacher Demo',
    demoParent: 'Parent Demo',
    demoStudent: 'Student Demo',

    // Admin Dashboard
    adminTitle: 'Academy Command & Control Center',
    totalStudents: 'Total Students',
    totalTeachers: 'Active Teachers',
    attendanceToday: "Today's Attendance Rate",
    feesCollection: 'Fee Collection Ratio',
    totalBilled: 'Total Billed Fees',
    totalCollected: 'Total Collected',
    totalPending: 'Outstanding Dues',
    publishNotice: '+ Publish New Notice',
    recentAuditLogs: 'Recent System Audit Trail',
    allStudentsDir: 'All Enrolled Students',
    academicYear: 'Academic Year 2026',

    // Teacher Dashboard
    teacherTitle: 'Teacher Portal & Gradebook',
    takeAttendance: 'Mark Daily Attendance',
    inputMarks: 'Enter Exam Marks',
    myAssignedClasses: 'My Assigned Classes & Subjects',
    markAllPresent: 'Mark All Present',
    submitAttendance: 'Save Attendance Sheet',
    saveMarks: 'Save Marks',
    subject: 'Subject',
    teacherRemarks: 'Teacher Remarks',

    // Parent Dashboard
    parentTitle: 'Parent Portal',
    selectChild: 'Select Child / Ward:',
    childOverview: 'Student Academic Overview',
    overallAttendance: 'Overall Attendance',
    currentGPA: 'Current GPA',
    dueFees: 'Pending Dues',
    payNow: 'Pay Fees Online',
    paidStatus: 'Paid',
    unpaidStatus: 'Unpaid',
    viewReportCard: 'View Report Card',

    // Student Dashboard
    studentTitle: 'Student Portal',
    digitalIdCard: 'Digital Student ID Card',
    todaySchedule: "Today's Class Schedule",
    examRoutine: 'Exam Timetable',
    admissionDate: 'Admission Date',

    // Payment Modal
    paymentModalTitle: 'Digital Fee Payment Gateway (Simulation)',
    selectMethod: 'Select Payment Method:',
    enterPhone: 'bKash / Nagad Wallet Number',
    enterPin: '4-Digit Simulation PIN (any)',
    confirmPayment: 'Confirm Payment of ৳',
    paymentSuccess: 'Congratulations! Your fee payment has been successfully recorded.',
    transactionId: 'Transaction ID',
    receiptDownload: 'Download Official Receipt'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('nextgen_lang') || 'bn';
  });

  const toggleLanguage = () => {
    const nextLang = lang === 'bn' ? 'en' : 'bn';
    setLang(nextLang);
    localStorage.setItem('nextgen_lang', nextLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['bn']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
